networks:
  apply-o-mat:
    external: false
    name: ${PROJECT_NAME}
  proxy_default:
    external: true

services:

  apply-o-mat_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: ${PROJECT_NAME}_frontend
    working_dir: /app/frontend

    # replace it
    command: 'tail -f /dev/null'

    container_name: ${PROJECT_NAME}_frontend
    volumes:
      - .:/app
    networks:
      - apply-o-mat
      - proxy_default
    environment:
      - DEBUG=true
      - ENVIRONMENT=default

      - VIRTUAL_HOST=frontend.${PROJECT_NAME}.servant
      - VIRTUAL_PORT=${FRONTEND_SERVER_PORT}
      - HOST_IP=${HOST_IP}
