networks:
  proxy_default:
    external: true

services:
  apply-o-mat_server:
    extends:
      file: docker-compose-server.yml
      service: apply-o-mat_server

    networks:
      - proxy_default

    volumes:
      - /root/projects/skwncr.net_storage/video:/app/frontend/dist/video
      - /root/projects/skwncr.net_storage/images/projects:/app/frontend/dist/images/projects

    command: 'npm start'
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - VIRTUAL_HOST=skwncr.net
      - VIRTUAL_PORT=${SERVER_PORT}
      - LETSENCRYPT_HOST=skwncr.net
      - LETSENCRYPT_EMAIL=matthias.kallenbach@skwncr.com