networks:
  apply-o-mat:
    external: false
    name: ${PROJECT_NAME}
  proxy_default:
    external: true

services:
  apply-o-mat_server:
    extends:
      file: docker-compose-server.yml
      service: apply-o-mat_server

    command: 'npm start'
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - VIRTUAL_HOST=skwncr.net
      - LETSENCRYPT_HOST=skwncr.net
      - LETSENCRYPT_EMAIL=matthias.kallenbach@skwncr.com