services:
  apply-o-mat_server:
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}_server
    working_dir: /app/server

    # replace this
    # command: 'npm start'
    command: 'tail -f /dev/null'

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
