networks:
  apply-o-mat:
    external: false
    name: ${PROJECT_NAME}
  proxy_default:
    external: true

services:
  apply-o-mat_server:
    extends:
      file: docker-compose-server.yml
      service: apply-o-mat_server

    # replace this
    command: 'tail -f /dev/null'
    #command: 'npm start'

    networks:
      - apply-o-mat
      - proxy_default

    volumes:
      - .:/app
      - /home/mk/projects/skwncr.net_storage/video:/app/server/static/video
      - /home/mk/projects/skwncr.net_storage/images/projects:/app/server/static/images/projects
      - /home/mk/projects/skwncr.net_storage/images/thumbs:/app/server/static/images/thumbs

    environment:
      - DEBUG=true
      - ENV=development
      - SERVER_PORT=${SERVER_PORT}

      - VIRTUAL_HOST=${PROJECT_NAME}.servant
      - VIRTUAL_PORT=${SERVER_PORT}
      - HOST_IP=${HOST_IP}
