networks:
  apply-o-mat:
    external: false
    name: ${PROJECT_NAME}
  proxy_default:
    external: true

services:
  apply-o-mat_frontend:
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}_frontend
    working_dir: /app/frontend

    # replace it
    # command: 'tail -f /dev/null'

    command: 'npm start'
    volumes:
      - .:/app
      - /home/mk/projects/skwncr.net_storage/images/projects:/app/frontend/public/images/projects:ro
      - /home/mk/projects/skwncr.net_storage/video:/app/frontend/public/video:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

    networks:
      - apply-o-mat
      - proxy_default
    environment:
      - DEBUG=true
      - ENVIRONMENT=default
      - FRONTEND_PORT=${FRONTEND_PORT}

      - VIRTUAL_HOST=frontend.${PROJECT_NAME}.servant
      - VIRTUAL_PORT=${FRONTEND_PORT}
      - HOST_IP=${HOST_IP}
